### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by tdoehmen** [tdoehmen/hypoparsr#1]
![till-demo](https://cloud.githubusercontent.com/assets/4321121/18354984/f589ce94-75e7-11e6-938e-f1fb561a67ec.gif)

**Comment by bedantaguru** [comment]
Do you have the excel with you?

**Comment by tdoehmen** [comment]
Hi Indranil,

 

Sorry, which Excel sheet are you referring to?

 

Best,

Till

 

Von: Indranil Gayen [mailto:notifications@github.com] 
Gesendet: Dienstag, 18. Februar 2020 08:09
An: tdoehmen/hypoparsr <hypoparsr@noreply.github.com>
Cc: tdoehmen <till.doehmen@web.de>; Author <author@noreply.github.com>
Betreff: Re: [tdoehmen/hypoparsr] Demo (#1)

 

Do you have the excel with you?

**Comment by bedantaguru** [comment]
Thanks @tdoehmen I have already recreated the excel from your animated GIF.

**Comment by tdoehmen** [comment]
Hi Indranil,

 

Sorry, which Excel sheet are you referring to?

 

Best,

Till

 

Von: Indranil Gayen [mailto:notifications@github.com] 
Gesendet: Dienstag, 18. Februar 2020 08:09
An: tdoehmen/hypoparsr <hypoparsr@noreply.github.com>
Cc: tdoehmen <till.doehmen@web.de>; Author <author@noreply.github.com>
Betreff: Re: [tdoehmen/hypoparsr] Demo (#1)

 

Do you have the excel with you?
